# Emit lib/site-urls.ts from recon.json
$recon = Get-Content -Raw "$PSScriptRoot\recon.json" | ConvertFrom-Json
$rootDir = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
$libDir = Join-Path $rootDir "lib"
if (-not (Test-Path $libDir)) { New-Item -ItemType Directory $libDir | Out-Null }

# Build canonical URL list (post types we care about; exclude 'unknown' = stale sitemap entries that 301)
$validTypes = @('pages','posts','events','news','webinar','leadership-team')
$canonicals = @()
foreach ($r in $recon.records) {
  if ($r.postType -notin $validTypes) { continue }
  if (-not $r.canonical) { continue }
  $canonicals += [pscustomobject]@{
    url            = $r.canonical
    postType       = $r.postType
    slug           = $r.slug
    datePublished  = $r.datePublished
    dateModified   = $r.dateModified
  }
}
$canonicals = $canonicals | Sort-Object url -Unique

# Build leadership redirects: stale-slug (root) -> canonical (/leadership-team/<slug>/)
# Source: recon.json records with postType=leadership-team — their canonical is /leadership-team/<slug>/.
# The legacy URL was /<slug>/.
$leadershipRedirects = @()
foreach ($r in $recon.records | Where-Object { $_.postType -eq 'leadership-team' }) {
  if (-not $r.slug -or -not $r.canonical) { continue }
  $from = "/$($r.slug)"   # Next.js redirects use no trailing slash
  $to   = ($r.canonical -replace 'https://sierradigitalinc.com','').TrimEnd('/')
  $leadershipRedirects += [pscustomobject]@{ from = $from; to = $to; slug = $r.slug }
}
$leadershipRedirects = $leadershipRedirects | Sort-Object from

# Emit TypeScript module
$ts = @"
// AUTO-GENERATED by docs/recon-data/_emit_site_urls.ps1 from recon.json.
// Do NOT edit by hand. Regenerate if recon.json changes.
// This is the single source of truth for sitemap.xml + redirect rules.

export type PostType =
  | "pages"
  | "posts"
  | "events"
  | "news"
  | "webinar"
  | "leadership-team";

export interface CanonicalUrl {
  url: string;
  postType: PostType;
  slug: string;
  datePublished: string;
  dateModified: string;
}

export interface LegacyRedirect {
  from: string;
  to: string;
  slug: string;
}

export const CANONICAL_URLS: readonly CanonicalUrl[] = $($canonicals | ConvertTo-Json -Compress -Depth 4) as const;

export const LEADERSHIP_LEGACY_REDIRECTS: readonly LegacyRedirect[] = $($leadershipRedirects | ConvertTo-Json -Compress -Depth 4) as const;
"@

$outFile = Join-Path $libDir "site-urls.ts"
$ts | Out-File -FilePath $outFile -Encoding utf8 -NoNewline
Write-Host "Wrote $outFile"
Write-Host "  Canonical URLs:        $($canonicals.Count)"
Write-Host "  Leadership redirects:  $($leadershipRedirects.Count)"
